version: '3.8'

services:
  backend:
    build: ./backend
    container_name: django_backend
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SECRET_KEY=testkey123
      - FRONTEND_URL=http://localhost:3000

  frontend:
    build: ./frontend
    container_name: nextjs_frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
